export const QUERY_KEYS = {
  // CATEGORIRES
  GET_ALL_CATEGORIES: 'GET_ALL_CATEGORIES',

  // PAYMENT METHODS
  GET_ALL_PAYMENT_METHODS: 'GET_ALL_PAYMENT_METHODS',

  // UNIT MEASUREMENTS
  GET_ALL_UNIT_MEASUREMENTS: 'GET_ALL_UNIT_MEASUREMENTS',

  // USER TYPES
  GET_ALL_USER_TYPES: 'GET_ALL_USER_TYPES',

  // KARDEX
  GET_ALL_KARDEXS: 'GET_ALL_KARDEXS',
  GET_KARDEX_ID: 'GET_KARDEX_ID',
  GET_KARDEX_BY_PRODUCT: 'GET_KARDEX_BY_PRODUCT',

  // USERS
  GET_USER: 'GET_USER',
  GET_ALL_USERS: 'GET_ALL_USERS',
  GET_USER_ID: 'GET_USER_ID',

  // CLIENTS
  GET_ALL_CLIENTS: 'GET_ALL_CLIENTS',
  GET_CLIENT_ID: 'GET_CLIENT_ID',

  // PRODUCTS
  GET_ALL_PRODUCTS: 'GET_ALL_PRODUCTS',
  GET_PRODUCT_ID: 'GET_PRODUCT_ID',
  GET_PRODUCT_NAME: 'GET_PRODUCT_NAME',
  GET_ALL_RETURN_TYPES: 'GET_ALL_RETURN_TYPES',

  // PROVIDERS
  GET_ALL_PROVIDERS: 'GET_ALL_PROVIDERS',
  GET_PROVIDER_ID: 'GET_PROVIDER_ID'
}
